[package]
name = "dir_walker"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["macros", "rt", "fs"] }
tokio-stream = { version = "0.1.12", features = ["fs"] }
